theme = "amberwood"

[editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[editor.indent-guides]
  render = true
  character = "▏"

[editor.lsp]
  display-messages = true
  display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-type", "total-line-numbers", "file-encoding"]
center = ["file-type"]
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
